services:
  database:
    container_name: postgres-db
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - docker-network

#  backend-api:
#    container_name: backend-api
#    build: ./backend
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/customer
#    depends_on:
#      - database
#    restart: unless-stopped
#    networks:
#      - docker-network
#
#  frontend-react:
#    container_name: frontend-react
#    build:
#        context: ./frontend
#        dockerfile: Dockerfile
#        args:
#            - REACT_APP_BACKEND_URL=http://localhost:8080
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend-api
#    restart: unless-stopped
#    networks:
#      - docker-network

networks:
  docker-network:
    driver: bridge